### PR TITLE
Adds meme - "Drakeposting"

### PR DESCRIPTION
**Pull request by Hornet-Wing**
#### Summary
This PR adds the "Drakeposting" meme for additional memeing!

Let me know if there are any issues.

### CODE REVIEW

**Comment by dipak-demansol** [comment]
@Hornet-Wing can you pls add more info about what should i have to test in this PR and i show that there is a duplicate meme of drake & drakeposting, both are same. please see the video

https://user-images.githubusercontent.com/89907719/141483545-2dfde5b3-c9d4-48de-b5cb-90f875845b83.mp4

.

**Comment by dipak-demansol** [comment]
@Hornet-Wing **drake & drakeposting**, Pls Remove The One command From That.

**Comment by catalintomai** [comment]
LGTM! @Hornet-Wing , please sync and merge.

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
Since they have the same prefix (is that the case with many aliases in the product?), I say we shorten to `drake` and get rid of the alias

**Comment by mickmister** [comment]
@Hornet-Wing Do you have any thoughts on my comment above?

**Comment by Hornet-Wing** [comment]
Yes, I'll make the changes now.

**Comment by Hornet-Wing** [comment]
Rebased and Updated.

For testing:
`/meme drake "Test in Staging" "Test in Prod"`

OR

`go run server/plugin.go -out demo.jpg "drake 'Test in Staging' 'Test in Prod'" && open demo.jpg`

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Meme name shorten to `drake` as expected
- No additional alias that starts with the same word
- Meme can accept 0, 1 or 2 strings as expected 
LGTM!

Thank you  @Hornet-Wing  for adding this 🎉 

@mickmister please merge when you have a chance

**Pull request merged**
