### PR TITLE
Add meme "overly attached girlfriend"

### PR DESCRIPTION
**Pull request by kscheel**
#### Summary
Adds the meme "overly attached girlfriend" :)

There somehow are a lot of changes in assets.go... Maybe because I ran `make memelibrary` in a Windows environment? Let me know if this is a problem. Otherwise I'll send a few more PRs with some other memes :)

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Thanks for the contribution :tada: 

The huge is of change come from the honestly quite messy make target. Would you mind manually removing the unrelated changes? Sorry for the inconvenience.

**Comment by kscheel** [comment]
wow, that was quick reply. Sure, I'll remove the unintended changes.

**Comment by kscheel** [comment]
oh, there still are a lot of changes my local diff tool didn't show me

**Comment by kscheel** [comment]
ok, I think it looks alright now? :)

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by hanzei** [comment]
Hmm, CI is failing. Could you please double check the syntax?

**Comment by kscheel** [comment]
sorry, I was a bit hasty with my diff tool, should have tried building again after the changes. Checks are now green :)

**Review by mickmister — APPROVED** [review]
LGTM thanks @kscheel!!

**Pull request merged**
