### PR TITLE
Release v1.3.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Cut release for Marketplace

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-memes/issues/27

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann Take your time to review this plugin. There is no need to rush it. This release should go into the Marketplace as `Beta`.

**Comment by DHaussermann** [comment]
@hanzei I have smoke tested this plugin The functionality seems to be in order and auto-complete functionality has been added. No issues found. 

However there do seem to be a couple issues with the build. 

1. When I run `make` I get 
```
env GO111MODULE=off /usr/local/go/bin/go get github.com/jteeuwen/go-bindata/...
/Users/dylanhaussermann/go/bin/go-bindata -o server/memelibrary/assets.go -pkg memelibrary -prefix server/memelibrary/assets/ -ignore '(^|/)\..*' server/memelibrary/assets/...
``` 
2. When I run `make all` I get 
```
@@ -1894,4 +1895,3 @@
 	cannonicalName := strings.Replace(name, "\", "/", -1)
 	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
 }
-
Gofmt failure
make: *** [gofmt] Error 1
``` 

Would it be appropriate to create follow-up issues for this rather than stopping the release? I'm not sure of the significance of this but, I'm assuming there is no impact on the compiled binary.

**Comment by DHaussermann** [comment]
Gentle ping on this @hanzei I know you were away last week. Must these build issues ☝️  be fixed before the release or, can this move forward to the market place?

**Comment by hanzei** [comment]
@DHaussermann Both build issues are not critical for the release.

1. Good catch! I've submitted https://github.com/mattermost/mattermost-plugin-memes/pull/29 to fix this.
2. with the fix from #29 this issue should be encountered so often. I've filled https://github.com/mattermost/mattermost-plugin-memes/issues/30 as a HW.

I think we are ready to ship, right?

**Comment by DHaussermann** [comment]
@hanzei yes,  correct.  Ready to ship.

**Pull request merged**
