### PR TITLE
Adding more memes

### PR DESCRIPTION
**Pull request by erdeerdeerde**
#### Summary

Add moar memes

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Thanks for adding more memes!

**Comment by dipak-demansol** [comment]
@hanzei **There is 2 different meme-Name that gives same meme-image**, i think we Should remove the "Computer-guy-thinking" & " fire!" meme-Name.

1) computer-guy
    Computer-guy-thinking

2) fire
    fire!

also it would be Great if i can choose the Text color, Why:- because, in some of the image black colour text not look that great, for example pls see this image.
image

**Comment by dipak-demansol** [comment]
@erdeerdeerde
 
1) computer-guy 
    Computer-guy-thinking

2) fire
    fire!

   Those are Duplicate Commands that gives the same meme, pls remove one command from both, as per me you can remove the "Computer-guy-thinking" & " fire!", computer-guy & fire command should work same as before. **Pls let me know if you have any Question.**

**Comment by erdeerdeerde** [comment]
@dipak-demansol done.

**Comment by dipak-demansol** [comment]
> @dipak-demansol done.

@erdeerdeerde `fire!` Command is removed, its good, but i can still see those 2 commands  **computer-guy & Computer-guy-thinking**, pls remove the `Computer-guy-thinking` Command.

**Comment by dipak-demansol** [comment]
@hanzei LGTM.

**Pull request merged**
